-- Create a table to track API usage per user per day
create table if not exists api_usage (
    id bigint generated by default as identity primary key,
    user_id text not null,
    date date not null default current_date,
    count integer not null default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    
    -- Ensure one row per user per day
    unique(user_id, date)
);

-- RLS Policies (Optional if using Service Role, but good practice)
alter table api_usage enable row level security;

-- Allow users to view their own usage (if we want to show it in UI later)
create policy "Users can view their own usage"
    on api_usage for select
    using (user_id = auth.uid()::text); -- Note: auth.uid() might be different with Clerk integration, adjust if needed or rely on Service Role for backend checks.

-- Allow Service Role full access (implicit, but for clarity)
-- No policy needed for service_role as it bypasses RLS.
